### ISSUE TITLE
[8.0] [account_easy_reconcile] partial reconciliation not working

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/account-reconcile#132]
In 8.0 partial reconciliation is not happening. In v7 it used to work.

Root cause:
base_reconciliation.py, in method "_reconcile_lines" calls to account move line method "reconcile" instead of "reconcile_partial".

**Comment by JordiBForgeFlow** [comment]
@damdam-s I can see that you did the migration to v8. Can you help me with this one?

**Comment by damdam-s** [comment]
@jbeficent According to https://github.com/OCA/bank-statement-reconcile/blob/8.0/account_easy_reconcile/README.rst, this module does not allow partial reconciliation. 
Maybe you want this module being migrated https://github.com/OCA/bank-statement-reconcile/pull/112

**Comment by JordiBForgeFlow** [comment]
@damdam-s  Not really. It is in account_easy_reconcile where a partial reconciliation method is called, but it's not used in the actual method. It is in the advanced reconciliation where the _reconcile_lines method of 'easy.reconcile.base' is called, but passing parameter allow_partial=True.

So I understand that this is a bug of this module, not the advanced reconciliation one, because the account_easy_reconcile should provide the option to call the partial reconciliation by other modules, such as the advanced.

I can create a PR for that.

**Comment by andreschenkels** [comment]
Jordi, 
Did you create the PR?
