### ISSUE TITLE
Provide bank statement reconciliation like Quickbooks

### ISSUE THREAD

**Issue by max3903** [OCA/account-reconcile#173]
https://www.youtube.com/watch?v=MgF2nkWvKCQ

Migrate the module account_banking_reconciliation originally made by Nova Point Group and maintained by Ursa Information Systems.

**Comment by pedrobaeza** [comment]
What is the advantage of this method over current one in Odoo? I see current very good.

**Comment by max3903** [comment]
@pedrobaeza Do you mean the out of the box one? Have you watched the video?

**Comment by max3903** [comment]
@pedrobaeza The advantage of this method is that it is the one of Quickbooks, which has a significant market share in the US. That's how US accountants do their bank reconciliation with Quickbooks and that's how some of them want to continue to do it in Odoo. This module aims to ease the transition.

**Comment by pedrobaeza** [comment]
I have watched again the video and find very odd the QuickBooks method, but anyway, as there's an opened PR for this, I close the issue.
