### ISSUE TITLE
allow_reconciliation on account with move_lines?

### ISSUE THREAD

**Issue by whulshof** [OCA/account-reconcile#215]
Would anybody know if there is an existing module, that makes it possible to switch allow_reconciliation on for accounts with existing move_lines.
If not would this be as simple as running the _amount_residual method for move_lines with this account? Or should I think of other things as well?

**Comment by whulshof** [comment]
I would be interested to create such a module, to be clear.

**Comment by travish2** [comment]
Hi whulshof, I had the same requirement, check out account_set_reconcilable: https://github.com/OCA/account-reconcile/pull/220
