### ISSUE TITLE
Put 8.0 branch as default and remove master

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/account-reconcile#28]
@yvaucher can you do this? Anyone?

**Comment by yvaucher** [comment]
As far as I know only members of the team https://github.com/orgs/OCA/teams/owners can do it.

**Comment by pedrobaeza** [comment]
OK, thanks. Let's see if anyone can do these operations, and we get this organized as soon as possible.

Regards.

**Comment by pedrobaeza** [comment]
Done.
