### ISSUE TITLE
[12.0] account_skip_bank_reconciliation breaks matching on payments

### ISSUE THREAD

**Issue by CasVissers-360ERP** [OCA/account-reconcile#304]
See video on runbot:
https://drive.google.com/file/d/141WuxkUkqNFjcALDnAzfmKtrhlqlEpGQ/view

When installing account_skip_bank_reconciliation payments are not matched anymore in bank statements.

@MiquelRForgeFlow @JordiBForgeFlow

**Comment by MiquelRForgeFlow** [comment]
Solved in https://github.com/OCA/account-reconcile/pull/305.
