### ISSUE TITLE
[12.0] How to allow to mix accounts receivable and payable in bank reconciliation?

### ISSUE THREAD

**Issue by josepmy** [OCA/account-reconcile#309]
Hello,
I need to get receivable and payable accounts in bank reconciliation, for example, to "confirming" operations where the banks advance the invoice and at the same time I must pay to the bank expenses and bank interest.

Salut,
Josep M

**Comment by pedrobaeza** [comment]
@josepmy please stop using GitHub issues as a forum for questions. This is not about any module in this repository nor for questions.

**Comment by josepmy** [comment]
Sorry. I guessed I could ask here.
