### ISSUE TITLE
[11.0] account_reconciliation_widget_partial module not do a partially reconcile.

### ISSUE THREAD

**Issue by MohsenWaleed** [OCA/account-reconcile#314]
Thanks for this module. I have tried this module and I was able to modify the amount and see the difference but when I click on Reconcile button and check the journal entry I see that the whole amount in the reconciled not the partial amount.

Please check the screencastify for my work:
https://drive.google.com/file/d/1WJB6A56D-thmlW_iL25P3moDvScTCJHu/view

Kindly check and advise if I understood the module function/logic correctly or not!

**Comment by Gabriel142** [comment]
I have the same problem, did you manage to fix it?

**Comment by MohsenWaleed** [comment]
@Gabriel142 No
