### ISSUE TITLE
V8 migration

### ISSUE THREAD

**Issue by Cedric-Pigeon** [OCA/account-reconcile#32]
Hello,

We suggest to start the migration by this way :
- merge of branch 7.0 with 8.0
- fix conflicts and commit 
- start modules migration one by one

Any other suggestions ?

Cédric

EDIT current migration status:
- [ ] account_advanced_reconcile @yvaucher (starting)
- [ ] account_advanced_reconcile_bank_statement
- [ ] account_advanced_reconcile_transaction_ref
- [ ] account_easy_reconcile @damdam-s #110 
- [x] account_invoice_reference
- [ ] account_payment_transaction_id
- [ ] account_statement_bankaccount_completion
- [ ] account_statement_base_completion
- [ ] account_statement_base_import
- [ ] account_statement_cancel_line
- [ ] account_statement_commission
- [ ] account_statement_completion_label
- [ ] account_statement_completion_voucher
- [ ] account_statement_ext
- [ ] account_statement_ext_point_of_sale
- [ ] account_statement_ext_voucher
- [x] account_statement_operation_multicompany
- [ ] account_statement_no_invoice_import
- [ ] account_statement_ofx_import
- [ ] account_statement_one_move
- [ ] account_statement_regex_account_completion
- [ ] account_statement_so_completion
- [ ] account_statement_transactionid_completion
- [ ] account_statement_transactionid_import
- [x] base_transaction_id

**Comment by pedrobaeza** [comment]
Hi, Cedric, what I'm going to do is to cherry-pick PEP8 fix into this branch, because there is going to be less conflicts than doing the merge, and then continue with the next step you mention. Please stay tuned, because I'm going to make the PR today.

Regards.

**Comment by Cedric-Pigeon** [comment]
We already merged it.
-> https://github.com/acsone/bank-statement-reconcile/tree/8.0-port-base-import

We prefer this way because cherry pick make branch diverge.

By this way, it remains possible to forward port from 7.0.

**Comment by pedrobaeza** [comment]
Cool! So please make the PR.

Thanks.

**Comment by lmignon** [comment]
forward port 7 to 8 in https://github.com/OCA/bank-statement-reconcile/pull/33

**Comment by pedrobaeza** [comment]
Merge done.

**Comment by Cedric-Pigeon** [comment]
Could please re-opened this issue. I would like to keep it open during the migration process.

Only the first and second steps of the process are closed.

Thanks.

**Comment by pedrobaeza** [comment]
OK, we'll use it as migration board.

Regards.

**Comment by Cedric-Pigeon** [comment]
The migration of some modules is not possible for the moment.
The serialized and sparse fields are not in the new API. An issue is currently assigned to Odoo dev team: odoo/odoo#1263

**Comment by pedrobaeza** [comment]
Yeah, I have seen it. We can workaround it using dedicated fields for each data that it's written, or implement this field again in a module that we depends on.

Regards.

**Comment by yvaucher** [comment]
Let's add list of modules and existing PR to have an overview

**Comment by yvaucher** [comment]
I'll start migrating **account_advanced_reconcile**

**Comment by ecino** [comment]
Hi all, do you know if there are any plans to migrate module `account_statement_completion`, knowing that `account_statement_ext` won't be migrated ?

**Comment by fclementic2c** [comment]
difficult I think with the new banking...

_camptocamp_

INNOVATIVE SOLUTIONS
BY OPEN SOURCE EXPERTS

_Frédéric Clementi_
Project Manager
Business Solutions

+41 21 619 10 41

www.camptocamp.com

2015-07-10 13:48 GMT+02:00 ecino notifications@github.com:

**Comment by ecino** [comment]
Completion is something we will definitely need, as we import huge statements (>500 lines) that we don't want to process manually.
I think we could either reintroduce bank statement profiles to do it like before, or build something new around parsers so that completion can be directly done during the import.

What do you think ?

**Comment by pedrobaeza** [comment]
The second approach is definitively the correct one. We have already done some completion while importing in spanish bank statement format: https://github.com/OCA/l10n-spain/tree/8.0/l10n_es_account_bank_statement_import_n43
