### ISSUE TITLE
Bank Statement reports have all Zero values - Odoo11 CE

### ISSUE THREAD

**Issue by niyshah** [OCA/account-reconcile#331]
Bank Statement reports have all Zero values except for Initial Balance in the Detail Report.

Recently upgraded client to Odoo11 CE. The bank reconciliation process works fine. It's just that the reports are blank in terms of amount. The detail report has every item, but zero values.

Install version of addon - 11.0.1.0.0

![Screenshot_20200814_112440](https://user-images.githubusercontent.com/54789283/90202355-cc87e800-de20-11ea-9c9e-e40103d376f2.png)
![Screenshot_20200814_112413](https://user-images.githubusercontent.com/54789283/90202357-cd207e80-de20-11ea-91e7-294e189193ef.png)

**Comment by niyshah** [comment]
Update - Removing the field options displays values.

`<span t-field="o.starting_balance"   t-options="{&quot;widget&quot;: &quot;monetary&quot;, &quot;display_currency&quot;: o.account_id.currency_id}"/>`

to 

`<span t-field="o.starting_balance"  />`

Python is not my strength, so can't debug further. The currency in use is AUD. It appears the formatting function is failing for some reason.

**Comment by niyshah** [comment]
By updating the formatting lines from 

`t-options='{"widget": "monetary", "display_currency": o.account_id.currency_id}'`

to 

`t-options="{'widget': 'monetary', 'display_currency': res_company.currency_id}"`

The reports now produce valid results.
Updated reports attached
[report_bank_statement_summary.txt](https://github.com/OCA/account-reconcile/files/5072425/report_bank_statement_summary.txt)
[report_bank_statement_detail.txt](https://github.com/OCA/account-reconcile/files/5072426/report_bank_statement_detail.txt)

**Comment by pedrobaeza** [comment]
Which module?

**Comment by niyshah** [comment]
Apologies, just noticed that, the account_banking_reconciliation module

**Comment by pedrobaeza** [comment]
@max3903 this one seems to be yours
