### ISSUE TITLE
Can't try bank_statement_journal_items module on Runbot (no menu leads to bank statements)

### ISSUE THREAD

**Issue by alexandreduf** [OCA/account-reconcile#336]
Hi,

I tried this module via runbot : https://github.com/OCA/account-reconcile/tree/13.0/bank_statement_journal_items

Here's  the problem : 
There is no submenu in Invoicing that leads to bank statements. Thus, it's impossible for a novice user (like me) to try this module via runbot.
![No_accounting_menu](https://user-images.githubusercontent.com/70237796/92984939-4345ee80-f47c-11ea-995b-210243afbcb1.png)

Thank you for your work!

**Comment by alexandreduf** [comment]
Hi,

It's me again. My previous post seems to be true for the whole project. I can't seem to find the "Accounting" menu in "Invoicing" in other modules.

Have a nice day!

**Comment by bosd** [comment]
Have you actived the "Show full accounting options"?
Go to debug mode.
Go to users -> click on your user -> settings and check "Show full accounting features"

**Comment by TeoGoddet** [comment]
Maybe we could activate it automatically on all accounting tests. (add admin to Show full accounting features) ?
