### ISSUE TITLE
[13.0][BUG] Why account_mass_reconcile allow reconcile items with move's status = Draft, Cancelled ?

### ISSUE THREAD

**Issue by kittiu** [OCA/account-reconcile#351]
This module has long history, but it does surprise me that it reconcile even cancelled items. Is this intentional? And what is the rational?

![image](https://user-images.githubusercontent.com/1973598/97333263-f5f7d200-18ad-11eb-918f-f4bad04116da.png)

**Comment by kittiu** [comment]
I have made the fix outside this module. If more people think this should be moved to core, I will do the PR.

Thanks!

**Comment by farazbdm** [comment]
obviously the mass reconcile should not be applied on the Cancel/ Draft entries,
@kittiu can you please share

**Comment by farazbdm** [comment]
@pedrobaeza can you please tag someone here who can resolve this issue

**Comment by luc-demeyer** [comment]
@kittiu 
Can you make a PR with you fix to avoid that cancelled and draft entries are getting reconciled ?

**Comment by kittiu** [comment]
Here you go, https://github.com/OCA/account-reconcile/pull/442
@farazc2h @luc-demeyer
