### ISSUE TITLE
Odoo (V13E) is not handling to mass reconcile records of 250k with account_mass_reconcile

### ISSUE THREAD

**Issue by jumshudsultan** [OCA/account-reconcile#362]
I've got more than 250k of records which I'm trying to do a mass reconciliation, but it's not happening due to timeout. Is there any way to process it by batches?

![image](https://user-images.githubusercontent.com/43217182/103486259-f795c700-4e15-11eb-9c3b-8297ba431d7e.png)

**Comment by farazbdm** [comment]
@jumshudsultan 
did you find a solution later, please share

**Comment by AaronHForgeFlow** [comment]
In Invoicing settings there is an option to commit each x transactions done:

![Image](https://github.com/user-attachments/assets/4e6c6c17-38dc-4f2b-8ca3-89e4c79d05b8)
