### ISSUE TITLE
Blank pdf report using account_banking_reconciliation

### ISSUE THREAD

**Issue by PRMA974** [OCA/account-reconcile#368]
Hello,
i am facing an issue on Odoo 12 community using account_banking_reconciliation module. PDF reports "bank Statement details" are blank/empty...I am wondering why ? Anyone may have an idea, please ? Thank you for developpement and attention. Laurent.
[Bank Statement-Detail (25).pdf](https://github.com/OCA/account-reconcile/files/6068457/Bank.Statement-Detail.25.pdf)

**Comment by supakornkim** [comment]
Hi,
I also face this issue.

**Comment by PRMA974** [comment]
@max3903 Hello Maxime, i am still trying to print bank statement report from account_reconcile module. Is there a way to do it properly ? My pdf report are empty...
Thanks for your answer. Regards, Laurent.

**Comment by PRMA974** [comment]
Hi. As a user (not a coder), i found half of a solution in 3-4 steps  :
1) Go to invoicing -> settings -> activate multi-currency
2) Go to bank statement -> click to modify account (small icon square) -> choose currency (to do that, you need the rights to write on res.bank.user -> technical setting -> model -> res.bak.user add rights)
3) Go to configuration -> technical settings -> report -> bank statement detail / summary -> choose html instead of pdf
4) You can now desactivate multi-currency if not needed

Still we have a problem for printing pdf on multiple pages...
