### ISSUE TITLE
[14.0] not possible reconcile after  odoo/odoo@80c2818

### ISSUE THREAD

**Issue by Mat-moran** [OCA/account-reconcile#375]
Hi, 

I do not know exactly if this issue should be post here or in odoo repository. 

The thing is that after this commit  was posted: https://github.com/odoo/odoo/commit/80c28189ae6b10ad17c4de2a781233a8ffe663a6#diff-1e3bd6be3bfb83a37ec9fb800ce8b1c95afe0be90ff792874ae7299c320a2f6e

I am not able to reconcile any journal item.
The steps to reproduce the error are the next ones:

1. Create an invoice (to reconcile with)
2. Create an item in a bank or cash journal
3. Publish the entry
3. Try to reconcile the invoice in the step 1 with the journal entry.
4. You get the error "The entry ... is already posted"

It seem that is due to the next line:
https://github.com/odoo/odoo/blob/1bf2e8805503d9bbebec58df9933abab3db70bd2/addons/account/models/account_move.py#L2436 

`if move.state == "posted":`
 `     raise UserError(_('The entry %s (id %s) is already posted.') % (move.name, move.id))`
  

What so you think? Any ideas of how to solve this?

Please let me know if I should put this issue in the odoo or is ok here.

**Comment by bosd** [comment]
Experiencing the same problem. Thanks for digging into the commits for possible causes.
The items cannot be reconciled and the " The entry .. is already posted" medsage is shown. But the bank statement for reconcilination has the status "processing"



This one might be interesting for  @ozono who did all the hard work on ```account_reconciliation_widget``` in https://github.com/OCA/account-reconcile/pull/359 

(Besides the point, I noticed that the progressbar is no longer there in V14.)

**Comment by bosd** [comment]
Just checked, it also happens on the runbot

**Comment by ozono** [comment]
I take note of that. I'll take a look ASAP.

**Comment by ozono** [comment]
Fixed in #377

**Comment by bosd** [comment]
Thanks for the very prompt action. However I am unable to update the module:
The operation cannot be completed: another model requires the record being deleted. If possible, archive it instead.

Model: Unknown (Unknown), Constraint: account_move_line_account_tax_rel_account_move_line_id_fkey

Any pointers how to solve?

**Comment by bosd** [comment]
Continued test on a different db.
The Validate button now triggers another error:

Error occured on statement lines imported with the module ```account_statement_import_camt```.
For testing purposes I created a manual statement on the same account. That one was able to reconcile.

Continuation in seperate issue. https://github.com/OCA/account-reconcile/issues/378
