### ISSUE TITLE
[14.0] Account Reconcile widget - Question: Backporting translations?

### ISSUE THREAD

**Issue by bosd** [OCA/account-reconcile#379]
Went trough the legwork of translating the module on weblate.
NL is finished now :tada: 
It was only after finishing it, found out that this is a backport and the translated strings are available in the old module.

Is there an posibility to also backport the translations for this module automatically?

Could save other translators a lot of work :wink:

**Comment by pedrobaeza** [comment]
Well, they can't be easily extracted automatically, but you can do the following: with POEdit, you can add previous version files to your translation memory, and then open the new PO, and get the program to auto-fill the matched terms.
