### ISSUE TITLE
[14.0] account_reconciliation_widget - analytic item no created 

### ISSUE THREAD

**Issue by rp-landoo** [OCA/account-reconcile#383]
When reconcile item is manually reconciled, if an analytic account is established, Odoo doesnt create any analytic item.
![Captura](https://user-images.githubusercontent.com/82085471/115726397-fcf62d80-a382-11eb-9a30-4086c3cb1fa9.JPG)

**Comment by sandi26** [comment]
@rp-landoo in my case its created analytic item but its have 2 same record i checked it and it seems there is a same line function(u can check on my attachment
![Screenshot from 2021-04-30 16-45-12](https://user-images.githubusercontent.com/40750702/116678587-aff20700-a9d3-11eb-8c1e-3fab57967ba1.png)
![Screenshot from 2021-04-30 16-44-12](https://user-images.githubusercontent.com/40750702/116678596-b1bbca80-a9d3-11eb-912e-1cce87a08b31.png)

**Comment by GorkaMagra** [comment]
This is still happening to this day, I'll explain a bit more how and when this does occur:

- If you manually add a new journal entry and select an analytic account to bind it, both the journal item and the analytic item will be created and the overall operation would be ok.

- However, if you reconcile an item and add it's analytic account throught the wizard provided on the dashboard (the window that we see on the image the first user sent ). The journal entry will be bound to that analytic account, the journal item would be successfully created but the analytic item related to that journal item WON'T be create, therefore, loosing all the analytic data.

**Comment by jonerikceberio** [comment]
Solved in #444
