### ISSUE TITLE
In-payment Status not visible

### ISSUE THREAD

**Issue by sargeleo** [OCA/account-reconcile#400]
in-payment status is not visible, are you guy's working on it as I cannot easily differentiate invoices whose payment are issued and waiting for reconciliation process. 

Thanks!

**Comment by pedrobaeza** [comment]
Sorry, this has nothing to do with this repository modules, or specify more.

Closing meanwhile.

**Comment by sargeleo** [comment]
@pedrobaeza Thank you for your prompt response. When I register payment against invoice/bill the payment status is supposed to change to "IN PAYMENT" and once account is reconciled it should change to "PAID". This functionality is apparently broken or unavailable in OCA reconcile module. Just need your feedback whether this is a work in progress or I need to configure some thing else in order to activate said functionality.

**Comment by pedrobaeza** [comment]
Which OCA module? Which Odoo version?

**Comment by sargeleo** [comment]
I'm using Odoo CE 14 and using this module https://github.com/OCA/account-reconcile/tree/14.0

**Comment by pedrobaeza** [comment]
I suppose you mean account_reconcile_widget, but meanwhile you don't give full instructions to reproduce the error, nothing can't be done.
