### ISSUE TITLE
[14.0] account_reconciliation_widget regex models client error

### ISSUE THREAD

**Issue by TeoGoddet** [OCA/account-reconcile#404]
Hi ! 
you can provide regex to find the amount of a suggested writeoff line.
But it seems the implementation is different between the backend (python) and the frontend (js)

Here we are matching the statement_line name (wich contain no useful infos (sequence generated move name)
    var matching = line.st_line.name.match(
           new RegExp(values.amount_string)
      );

https://github.com/OCA/account-reconcile/blob/bbbffd3eb47dcdfda5ab75dfbc89df2542e663ff/account_reconciliation_widget/static/src/js/reconciliation/reconciliation_model.js#L1601

and there they are matching the statement payment_ref
                match = re.search(line.amount_string, st_line.payment_ref)
https://github.com/odoo/odoo/blob/b36809315f12142ca9589b34b38c725100528909/addons/account/models/account_reconcile_model.py#L346

I will locally test
    var matching = line.st_line.payment_ref.match(
           new RegExp(values.amount_string)
      );

Is there a reason for redoing this calculation on the server ? Should not we retrieve it from the server ? 

Need help to choose the fix (small fix or rewrite to load from backend) and then may be able to submit PR

**Comment by TeoGoddet** [comment]
I'm also sceptic about this line which mess up my number (i have . as decimal separator in my model)
https://github.com/OCA/account-reconcile/blob/bbbffd3eb47dcdfda5ab75dfbc89df2542e663ff/account_reconciliation_widget/static/src/js/reconciliation/reconciliation_model.js#L1606

**Comment by TeoGoddet** [comment]
The fix is working on my installation, should i open a MR ?

**Comment by Tardo** [comment]
Hi @TeoGoddet
As you say, I don't see any inconvenience in moving the logic to Python. But I think it is better to do it in a new version since it involves having to change the sync. calls to async.

In current versions I think it is more appropriate to apply the fix for the construction of the regex.

**Comment by TeoGoddet** [comment]
Ok, i'll do the PR

**Comment by TeoGoddet** [comment]
See #412
