### ISSUE TITLE
V14 account_reconciliation_widget show moves in cancel status

### ISSUE THREAD

**Issue by ocandoe** [OCA/account-reconcile#429]
## Module
account_reconciliation_widget

## Describe the bug
When you have accounting entries in a canceled state, they are still shown in the lines to reconcile in the bank statements.

## To Reproduce

1. Create an entry and cancel
2. Create a bank statement and reconcile
3. You can see all line include the cancel

**Expected behavior**

**Additional context**
V14 CE

![Cancel 2](https://user-images.githubusercontent.com/44589940/147715554-4a4881b3-d370-4ec3-80fd-a4e549f417b0.jpeg)
![Cancel 1](https://user-images.githubusercontent.com/44589940/147715558-32a35e36-07fd-40fc-a1e0-9077b344d039.jpeg)

**Comment by andrewdhastings** [comment]
This is still an issue, does anyone have a fix for this?

**Comment by andrewdhastings** [comment]
New merge request to fix issue: https://github.com/OCA/account-reconcile/pull/451
