### ISSUE TITLE
Automatic reconcile delete and replace some partial reconcile done by user manually

### ISSUE THREAD

**Issue by vrenaville** [OCA/account-reconcile#43]
Automatic reconcile delete and replace some partial reconcile done by user manually

To reproduce:
- Create a customer invoice for 10000 € to Customer X (customer account: 4110000) - Add a reference : ABC1234 and validate the invoice to book it into ledger
- Pay partialy that invoice (8000€) using the bank statement...but fill in a different reference (XYZ789) - Confirm the bank statement - the payment entry will be posted.
- Reconcile manually the invoice and the partial payment
- Create a new bank statement to record a 2nd partial payment for that invoice (1500€) but this time the reference is the same than the one use on the invoice entry (ABC1234) .
- Lauch the automatic reconcile on the receivable account

The bug is the following:
- The system will create a partial reconcile between the invoice and 2nd payment without including the 1st payment done manualy reconciled (because this one do not have the same reference).
- the initial partial reconcile is broken because linked to only 1 account move line (the other one being now reconciled with the 2nd payment)

**Comment by fclementic2c** [comment]
+1
This is a big problem we face today with the advanced reconcile module. 
Users expect the system not altering reconciliation manually created !

**Comment by pedrobaeza** [comment]
Do you have a PR?

**Comment by laetitia-gangloff** [comment]
Hello,

I have the following use case :
- an invoice payment
- an invoice fee
- a bank statement

When bank statement is not loaded, the invoice payment and invoice fee are partially reconciled automatically.
Then the bank statement comes. I want the reconciliation take account of the preceding partially reconciled move.

With the proposed fix, it is not the case. Is it possible to propose an option that allow or not (default is not) to rewrite partial reconciled item ?
