### ISSUE TITLE
[14.0] account_reconcile_widget missing tax grid entry in created journal items

### ISSUE THREAD

**Issue by tv-openbig** [OCA/account-reconcile#432]
In day-to-day accounting work, there can always be direct debits from suppliers for whom there are no direct incoming invoices (contracts, etc.). These are usually posted to an expense account using the bank statement instead of a supplier invoice. In addition to the expense account selection on manual operations tab, the reconcile widget also allows you to choose a tax (e.g. 19% input tax incl. In price). The posting to the input tax account takes place smoothly, but the field tax_tag_ids (field is named as "tax grids") must also be filled. With "19 input tax inl. In price" this would be, for example, "-66". This code is required for the monthly tax report (advance VAT return), otherwise incorrect values ​​would be transmitted.

This function is included in the Reconcile Widget of the Odoo Enterprise Edition. 

The video shows this clearly and compares to the correct way in Odoo EE:
https://drive.google.com/file/d/15kJe-KS1u2GDRaXLWi6o5XJKGjdwUOXs/view

**Comment by TeoGoddet** [comment]
Maybe similar to #418, need further checks

I will try to propose a PR to switch the logic of the reconciliation to the server side, it would also solve #420

**Comment by fkantelberg** [comment]
@TeoGoddet @tv-openbig 
I tried your suggested commit but it wasn't working. I found out that the tax_tag_ids are missed somewhere between the tax and the account.move.line and I suspect a renaming of it. It would be nice if you could test #440 as this resolves the issue for me.
