### ISSUE TITLE
Error: QWeb2: Template 'reconciliation' not found

### ISSUE THREAD

**Issue by widiyanto020291** [OCA/account-reconcile#467]
Error: QWeb2: Template 'reconciliation' not found
exception@http://localhost:8069/web/content/616-6d033f7/web.assets_common.js:4408:7
_render@http://localhost:8069/web/content/616-6d033f7/web.assets_common.js:4453:103
render@http://localhost:8069/web/content/616-6d033f7/web.assets_common.js:4449:151
renderElement@http://localhost:8069/web/content/625-c2d5f68/web.assets_backend.js:488:452
OdooClass.extend/</prototype[name]<@http://localhost:8069/web/content/616-6d033f7/web.assets_common.js:4646:488
_widgetRenderAndInsert/<@http://localhost:8069/web/content/616-6d033f7/web.assets_common.js:4988:6

**Comment by pedrobaeza** [comment]
Steps to reproduce the problem in runboat?

**Comment by einstom** [comment]
faced with the same issue.

**Comment by Ahmed-Sabri** [comment]
Same here .. 

![image](https://user-images.githubusercontent.com/108468895/194285494-cd1233f5-13d7-46e2-9353-4c1fe7919fad.png)

**Comment by pedrobaeza** [comment]
Nobody is saying if reproducible on runboat (which is not AFAIK), so closing. Your problem may be that you are using the "Import module" option, which is not valid.

**Comment by KenjxJJ** [comment]
The upgrade to the accounting module(odoo mates version) which is later to installation of the widget solves the problem.
