### ISSUE TITLE
account_reconciliation_widget label match decimal_separator broken

### ISSUE THREAD

**Issue by jordens** [OCA/account-reconcile#478]
The regexp that is meant to remove everything that is not a digit or the decimal separator from the label match is broken.

https://github.com/OCA/account-reconcile/blob/a29c6fc9c1cccbb287334a78cd0f17eee9013f5b/account_reconciliation_widget/static/src/js/reconciliation/reconciliation_model.js#L1606

This was fixed in the server side model in https://github.com/odoo/odoo/commit/d4da8be3669fbfdfdcad752af1f0311accaf34a3

The same fix should be applied in the `js`.

Tested that this works and that it fixes the issue.

**Comment by pedrobaeza** [comment]
Can you please propose the needed change in a pull request?

**Comment by TeoGoddet** [comment]
Hi, see https://github.com/OCA/account-reconcile/pull/420 and review it if you can.
