### ISSUE TITLE
Reconciliation screen shows draft vendor bills

### ISSUE THREAD

**Issue by me-Lee** [OCA/account-reconcile#485]
account_reconciliation_widget 

## Describe the bug
Reconciliation screen includes draft vendor bills

**Affected versions**:
15.0.1.1.2

1. Create a vendor bill, save but do not confirm
2. Load reconciliation screen and you will see the draft vendor bill waiting to be reconciled
3.

**Expected behavior**
I would not expect to see a 'draft' vendor bill in the reconciliation screen, only posted bills.

**Additional context**

**Comment by pedrobaeza** [comment]
Do you have latest version? Since this commit: https://github.com/OCA/account-reconcile/commit/f343ccfa3c09b3b206f49b2735b0f58068302b45, it should happen.

**Comment by me-Lee** [comment]
I have just found the latest version on here & it has fixed the problem. I'm new to github & didn't realise that the version here is newer than OCA version. Thank you for your help.
