### ISSUE TITLE
Impossible to click on "Manual Operation" tab with fr_FR user

### ISSUE THREAD

**Issue by clementmbr** [OCA/account-reconcile#486]
## Module
account_reconciliation_widget

## Describe the bug
Impossible to click on tab "Manual Operation" when trying to reconcile a bank.statement with amount over 999 (and user not with en_US language). 
JS Error message : 
"Uncaught Error: « 1 000,00 € » n'est pas un champ monétaire valide"

## To Reproduce
**Affected versions**: 14.0

1. Set your user's language on fr_Fr 
2. Create a bank.statement with a bank.statement.line  with a value of 10 000€
3. Click on Validate/Reconcile bank.statement
4. Try to click on "Manual Operation"

**Expected behavior**
No error message.

**Additional context**
If the user language is en_US then the value is displayed as "10,000.00€" and there is no error message.

**Comment by pedrobaeza** [comment]
Are you sure you have latest code? cc @TeoGoddet

**Comment by clementmbr** [comment]
@pedrobaeza Yes I double checked that.
But I just discovered that @TeoGoddet touched the regex number part few days ago before opening this issue. 
Might have broken something...

**Comment by clementmbr** [comment]
I tried to fix the bug by myself, but I couldn't reproduce the bug on my local desktop... Maybe it's just a conflict on assets... I'll check later...

**Comment by clementmbr** [comment]
@pedrobaeza @TeoGoddet finally I did manage to repeat the bug on a local odoo. So it's a real bug. I'm trying to fix it.
If you have an idea of the origin, let me know! :)

**Comment by pedrobaeza** [comment]
Isn't this problem due to https://twitter.com/alexisdlattre/status/1554758998456692736?s=20&t=UtQHqkI3B7NVl8Sq_hg23g ?

**Comment by clementmbr** [comment]
@pedrobaeza it's definitely due to this! Thanks for sharing the info. :pray: I'll talk to Alexis to understand how to fix this.
If you're ok with this, I'll let the issue opened until the problem is solved (even if it's not a problem due do the account reconcile widget directly).

**Comment by pedrobaeza** [comment]
Well, I prefer to clean this issue in this repo, as it's not related. Please open the issue at Odoo.

**Comment by clementmbr** [comment]
I tought it could help other people who would face this bug through the widget as I did.
But if you prefer I can close it. No problem.

**Comment by alexis-via** [comment]
You can follow the comments here https://github.com/odoo/odoo/pull/90191 and the PR that is supposed to fix the regression in v14 here https://github.com/odoo/odoo/pull/97462
