### ISSUE TITLE
[14.0] account_reconciliation_widget : missing analytic account in manual reconcile interface

### ISSUE THREAD

**Issue by alexis-via** [OCA/account-reconcile#503]
This bug is a regression that I introduced in this PR:
https://github.com/OCA/account-reconcile/pull/487/files

Scenario of the regression:
- go to Journal Items
- selection several journal items from the same account that are NOT balanced
- click on "Action > Reconcile"
=> odoo opens the manual reconciliation interface
- in the tab "Manual Operations", you don't see the field "Analytic account"

The bug is caused by this change: https://github.com/OCA/account-reconcile/pull/487/files#diff-6e45d1c3f26a883431be8c8affef6e88a277ba4a4e24347751d0d1fefab73c60L387

I'll try to fix this regression.

BTW, I often think that we should not use the special reconciliation widget when doing a manual reconcile from "Action > Reconcile" of Journal Items. It was faster when the good old wizard account.move.line.reconcile that existed up to v11 (code in v10: https://github.com/odoo/odoo/blob/10.0/addons/account/wizard/account_reconcile.py)

**Comment by bunhin** [comment]
@alexis-via any news on this fix, i am sorry to ask

**Comment by alexis-via** [comment]
@bunhin I now use my new module account_move_line_reconcile_manual so I don't have the pb any more. Easier and faster too ! https://github.com/OCA/account-reconcile/tree/14.0/account_move_line_reconcile_manual

**Comment by bunhin** [comment]
I see, so @alexis-via,  for all journal items that have no payment records, (manual reconcile) you use [account_move_line_reconcile_manual],?
