### ISSUE TITLE
[15.0] [account_reconciliation_widget] Foreign Currencies in Bank Statement Line is not recognize

### ISSUE THREAD

**Issue by singwangho** [OCA/account-reconcile#522]
## Module
account_reconciliation_widget

## Describe the bug
If the bank account is configured to multi-currency (i.e. the currency for the account is not set), when using reconcile, the widget's "bank statement line" erroneously returns the foreign currency as company's currency.  Reconciliation is not possible.

## To Reproduce
**Odoo15**:

The behavior is reproduced with demo data.  Steps to reproduce the behavior:
1. Load demo data
2. Load the modules: om_accountant_account and account_reconciliation_widget)
3. Add new bank account
4. Add a new bank statement with line information: Label="Receive Euro 50", Amount Currency=50.0; Foreign Currency=EUR; Amount=54.0
_5. For clarity, I have changed currency symbol of USD from "$" to "US$"._
6. Click "Post" and then "Reconcile'
7. Note in the statement line amount it show US$50.00 instead of EUR50.  Note when rollover the 'i' the Amount shown is also incorrect.

**Expected behavior**
For the statement line amount, I expect the line to show line's currenct which is EUR50.  And that it is reconciling against EUR50 instead of US50.

**Additional context**
N/A

**Comment by singwangho** [comment]
Hi, I did some digging and found that this module "account_reconciliation_widget" doesn't read in AccountBankStatementLine.**foreign_currency_id** at all.

So generally it doesn't really support individual line's foreign currencies...

Below edits _models/reconciliation_widget.py_ should give the minimum support for the 'foreign_currency_id' field in statement line.

### Suggested FIX
diff account_reconciliation_widget/models/reconciliation_widget.py
1021,1023c1021,1023
\<         if st_line.amount_currency and st_line.currency_id:
\<             amount = st_line.amount_currency
\<             amount_currency = st_line.amount
\---
\>         if st_line.amount_currency and st_line.foreign_currency_id:
\>             amount = st_line.amount
\>             amount_currency = st_line.amount_currency
1025c1025
\<                 self.env, abs(amount_currency), currency_obj=statement_currency
\---
\>                 self.env, abs(amount_currency), currency_obj=st_line.foreign_currency_id

**Comment by whotopia** [comment]
I have the exact same issue for Odoo 14 CE.  
I am trying to do a 7000 GBP transfer from GBP account to CHF Account.   
To do this in Odoo 14, I perform 2 transfer operations. One for each account via the transfers account.  
    These 2 operations create 2 Journal entries which work between BankAcct Outstanding Receipts and  Internal bank transfers account
    I then reconcile these 2 operations.  

Then, I have a bank statement line (e.g. in the CHF receiving account). 
    When the statement is posted, the line creates a journal entry between the actual bank account GL, and the associated bank suspense account.       
    
So reconciliation should create a journal entry between the Outstanding Receipts account and the bank suspense account.  

Also, as the amount we get from the European Central bank exchange rate will be different from the actual rate given by the bank we need to set up a reconciliation model to assign that difference to some kind of currency gain/loss account.  

So far nothing I have listed above is odd and it all aligns with the documentation on how Odoo 14 bank transfers between differing currency accounts should work.   

However, here now is the bug.  When I try to reconcile in the CHF account, I see the following:

![Screenshot 2023-03-15 at 16 31 49](https://user-images.githubusercontent.com/9039050/225362044-d35482f4-2d6c-4e8f-b01a-0ff53f4ed800.png)

The widget is reporting wrong currency, AND is not allowing me to reconcile with the correct difference amount for the FOREX.   This is a bug.  Please help!!!

**Comment by whotopia** [comment]
In my own case, the issue was coming from the reconciliation widget within CybroSys full accounting kit.   
I posted this   https://github.com/CybroOdoo/CybroAddons/issues/246 
 but more importantly found this:  
    https://github.com/CybroOdoo/CybroAddons/issues/177
    which fixed the issue for me within the CybroSys code.  
 Is it possible that the OCB account_reconciliation_widget has a similar issue??

**Comment by singwangho** [comment]
Yes, seems like the same issue and the fix seems like similar lines of codes.

I opened a pull request with more details #531.

**Comment by whotopia** [comment]
> Yes, seems like the same issue and the fix seems like similar lines of codes.
> 
> I opened a pull request with more details #531.

If you haven't already seen this, also note https://github.com/CybroOdoo/CybroAddons/issues/245 .  I have seen this weird interaction between the Cybrosys Reconciliation Widget and the one from OCA.  Perhaps some kind of namespace issue ?  

In any case, if you are debugging the above, and happen to have both OCA account-reconcile/account_reconciliation_widget and CybroAddons/base_accounting_kit installed, you will likely see the same issue I'm reporting.   If you can figure out why it would be grand!  Ideally it would be nice to be able to install both these addons with no negative interactions.
