### ISSUE TITLE
Error installing account_reconciliation_widget v15

### ISSUE THREAD

**Issue by droidosergioh** [OCA/account-reconcile#523]
Right after you install the module account_reconciliation_widget you get this error:

Uncaught (in promise) Error: Template reconciliation.done already defined
    at QWeb._addTemplate (web.assets_common.min.js:1007:58)
    at QWeb.addTemplates (web.assets_common.min.js:1006:81)
    at web.assets_backend_prod_only.min.js:11:2092

**Affected versions**: v15

1. Install the module
2. The window gets blank
![image](https://user-images.githubusercontent.com/15266734/219391712-d666e6e8-b8e8-4217-9ae7-791b1e6fdf20.png)

4. Inspect element with the browser and you can see the error message

**Expected behavior**
The ERP should load as normally

**Additional context**
Using some EE modules

**Comment by pedrobaeza** [comment]
Incompatibility between installed modules, specially with EE `account_accountant`. Nothing that can be done. You have to choose.

**Comment by droidosergioh** [comment]
@pedrobaeza thanks!
