### ISSUE TITLE
[15.0][account_reconciliation_widget] User Error: cannot create unbalanced journal entry; differences debit - credit [-0.01]

### ISSUE THREAD

**Issue by nicolas-tg** [OCA/account-reconcile#528]
## Module
account_reconciliation_widget

## Describe the bug
I am facing a User Error: "Cannot create unbalanced journal entry. Ids: [55]
Differences debit - credit: [1e-06]"

## To Reproduce
**Affected versions**: 15.0

1. My Company Currency is HKD with Rounding 6 digits, and the USD Currency is only 2 digits
2. I use 2 bank accounts with each currency and hence, two journals.
3. I create an invoice (INV/2023/00006) for a total of 368.282,64 USD and add 3 payments of equal amount (3 times 122.760,88 USD). The invoice is full paid.
4. I Create a Bank Statement for the Journal USD, with the one payment of 368.252,64 USD (It's deducted of 30 USD of Bank Charges).
5. I try to reconcile with 3 payments made in Odoo and the Bank Charges. The totals in USD balance each other correctly.
6. But I face this User Error: "Cannot create unbalanced journal entry. Ids: [55]
Differences debit - credit: [1e-06]"

![Capture d’écran 2023-02-24 à 13 22 26](https://user-images.githubusercontent.com/99798707/221107122-eaa3ecfd-2d8b-489f-a28a-9249763e984d.png)

Note: on my production database, it shows "Differences debit - credit: [-0.01]" because I used different currency exchange rates and dates...

**Expected behavior**
If my reconcilation is correct in the currency I use for the bank statement, the payments, etc. then it should be possible to validate this reconcilation without facing this error.

**Additional context**
A quick workaround, which is not acceptable is to add 4 digits to the USD currency, but this will show 4 digits to any documents, records or views using USD.

**Comment by singwangho** [comment]
Seems like there is a rounding difference where the Total of 3 Invoices is different from Bank Statement total.

Perhaps check in Settings -> Accounting -> "Default Accounts" and make sure you have a journal selected for exchange difference?  If you don't have one, make a Miscellaneous one.  Also check whether Gain Account and Loss Account is properly selected so rounding differences can post there.

**Comment by nicolas-tg** [comment]
I forgot to mention these parts, but yes, indeed it was correctly configured in Odoo:
- "Default accounts" had a Journal for Exchange Difference, type "Miscellaneous
- Gain and Loss accounts also properly set.

**Comment by oreju** [comment]
Following, same issue with v14

**Comment by zonclayv** [comment]
I confirm, I have the same problem with v14.
It seems that there is no logic related to with processing the exchange rate difference when reconciling bank statements.

Are there any workarounds or suggestion hot to fix it?
