### ISSUE TITLE
[16.0] account_reconcile_oca: Add list view

### ISSUE THREAD

**Issue by svenv** [OCA/account-reconcile#548]
## Is your feature request related to a problem?
Editing a transaction amount, or removing it, takes several steps involving editing or canceling and deleting the journal entry itself.

## Describe the solution you'd like
Enable list view to be able to easily edit and remove transactions, see the running balance, as well as edit the related statement.

### Ability to switch to List view:
![image](https://github.com/OCA/account-reconcile/assets/913827/28b2872e-6d6d-4ebe-910c-71ab8c109561)

### List view example:
![image](https://github.com/OCA/account-reconcile/assets/913827/5cc22a62-c194-4f52-8d3f-f5f3c4cc5524)

## Describe alternatives you've considered
We currently click "View Move" to open the journal entry, then either edit the amounts or cancel and delete the journal entry.

**Comment by kaleemullah786** [comment]
hey i want to work on it. can you provide more details

**Comment by svenv** [comment]
Hi @kaleemullah786 , I've added an example screenshot of the list view. Let me know if this helps.

**Comment by kaleemullah786** [comment]
kindly provide the path to this page

**Comment by svenv** [comment]
![image](https://github.com/OCA/account-reconcile/assets/913827/4f6d4b2c-c48f-4a9d-b54d-b12c42ecb8b3)

On a new Odoo 16 CE install, you will most likely find it under yourdomain.com/web#cids=1&menu_id=115&action=283&active_id=6&model=account.bank.statement.line&view_type=kanban

List view example (Enterprise):
https://41550010-16-0-all.runbot148.odoo.com/web#active_id=7&model=account.bank.statement.line&view_type=list&menu_id=633&cids=1
