### ISSUE TITLE
[16.0] account_statement_base: can't edit starting and closing balance of a cash statement

### ISSUE THREAD

**Issue by svenv** [OCA/account-reconcile#549]
## Module
[account_statement_base](https://github.com/OCA/account-reconcile/tree/16.0/account_statement_base), [account_reconcile_oca](https://github.com/OCA/account-reconcile/tree/16.0/account_reconcile_oca)

## Describe the bug
Not able to edit the Starting and Ending Balance of a cash statement. Because of this, you can't easily fix issues with statements (ie. ending balance not corresponding with computed ending balance).

## To Reproduce
**Affected versions**: 16.0

1. Register a transaction on a cash journal with a statement assigned
2. Open the statement of the cash journal
3. While you can see when your statement is not in order (shows red), you can't edit the balances to fix it.

**Expected behavior**
Ability to edit the balances of the statement. It would be great if we could see the relevant transactions of the statement as well.

**Comment by Nendiksi** [comment]
Hi all,
Any progress on this, currently i'm on 16.0.1.2.4 version, the issue still exist. Need helps....tq
