### ISSUE TITLE
[14.0][15.0] account_reconciliation_widget: Due date shown on proposition lines

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/account-reconcile#563]
The reconciliation widget is showing the due date in the proposition lines instead of the journal item date.

![Selección_064](https://github.com/OCA/account-reconcile/assets/7165771/ef06a0e6-a461-423f-82eb-5760214102cb)

![Selección_065](https://github.com/OCA/account-reconcile/assets/7165771/a3b37256-a1f9-4917-a724-1c5a956ddde6)

It has been this way since a lot of time, but it seems weird.

What do you think about changing it to the journal item date?

@Tecnativa TT43815

**Comment by pedrobaeza** [comment]
cc @alexis-via @JordiBForgeFlow @luc-demeyer @rvalyi @sbidoul @etobella

**Comment by etobella** [comment]
Well, both dates are important... Sometimes due date can be more representative than the original date 🤔

**Comment by sbidoul** [comment]
My first intuition is that the journal item date would be more natural. Do we know what Odoo Enterprise does?

cc/ @gva-acsone

**Comment by pedrobaeza** [comment]
It seems that in enterprise v15 is showing the due date as well:

![Selección_066](https://github.com/OCA/account-reconcile/assets/7165771/7f3b5cf9-6edd-4385-aa0c-ba951e446375)

![Selección_067](https://github.com/OCA/account-reconcile/assets/7165771/cea1a43f-4e2f-4699-8a7f-568b7173d6d2)

On v16 enterprise, the rules change, as they show a list view, but it's curious that the accounting date is shown in third place, and the due date is optional="hide":

![Selección_068](https://github.com/OCA/account-reconcile/assets/7165771/9276c6bb-a10e-4465-a24c-d75d22c5a6f2)
