### ISSUE TITLE
[16.0] notes filed missing from the new reconciliation widget: account_reconcile_oca

### ISSUE THREAD

**Issue by nagybal** [OCA/account-reconcile#572]
**Is your feature request related to a problem?**
I would like to see the "Notes" fields as well, while doing the reconciliation. The notes field is missing from the new reconciliation widget: https://github.com/OCA/account-reconcile/tree/16.0/account_reconcile_oca
![Screenshot 2023-08-15 at 18 40 13](https://github.com/OCA/account-reconcile/assets/27618042/a3afdf7d-ca84-4367-8d9e-8e3d20c9c3dc)

**Describe the solution you'd like**
I would like be able to change the fields. Please activate this small tool on the view:
![Screenshot 2023-08-15 at 18 35 45](https://github.com/OCA/account-reconcile/assets/27618042/08221dfd-ac77-4295-bd12-25862c33512d)

**Describe alternatives you've considered**
If there would be an option at the settings, to active this filed on the left side, on the list: I believe it would work fine. I am open for other suggestions.

**Additional context**
Please do apologise if I am missing something and this feature already exists.

**Comment by nagybal** [comment]
@pedrobaeza please confirm if this is a valid request

**Comment by pedrobaeza** [comment]
Not sure if that can be achieved easily, but it gets annotated for anyone to see it.

**Comment by nagybal** [comment]
@pedrobaeza thank You for responding. How about to show the note in a mouseover. Hovering the statement lines on the lefthand side?

**Comment by pedrobaeza** [comment]
I'm not the one who has developed it, so I can't say. The issue is opened for other contributors or the original author to check.

**Comment by etobella** [comment]
What is this notes field? It does not exist on account.move.line on 16.0...

**Comment by nagybal** [comment]
> What is this notes field? It does not exist on account.move.line on 16.0...

It is called narration on the account.bank.statement.line

![Screen Shot 2023-08-26 at 23 23 11](https://github.com/OCA/account-reconcile/assets/27618042/058d274e-4f3c-4efd-b488-974288b0289c)

**Comment by nagybal** [comment]
@etobella it would be nice to have the narration collumn 👍

**Comment by etobella** [comment]
Ok, but narration is not on the lines, should be shown as an extra page in the notebook. WDYT?

**Comment by nagybal** [comment]
We are talking about this field of the statement lines:
![Screenshot 2023-09-06 at 9 45 17](https://github.com/OCA/account-reconcile/assets/27618042/ff7888f5-0237-4e44-b676-3b039e76df46)

I was thinking about this. There could be a lot of info in these fields. How about instead of a column, just show the notes/narration field here on the card: 
![Screenshot 2023-09-06 at 9 39 31](https://github.com/OCA/account-reconcile/assets/27618042/d03f4f49-ac3e-462d-a451-e24df22b0baf)

**Comment by etobella** [comment]
narration is a field for account.bank.statement lines, you are trying to use it on account.move.line, the field is not there. My recommenadation would be to add a new tab (after Manual Operation for example) that includes the narration field.

WDYT?
