### ISSUE TITLE
[16.0] account_reconcile_oca pulls the amount in foreign currency from the wrong field of the statement line

### ISSUE THREAD

**Issue by nagybal** [OCA/account-reconcile#574]
## Module
account_reconcile_oca

## Describe the bug
When I import a bank statement in a different currency into Odoo, the information looks okay. However, when I try to reconcile, the amount changes to the one in the main currency instead of using the original amount. This makes it impossible to match statements in different currencies. But when I check the transaction details, the amount is still right.

**Additional context**
I have two bank account, one in a foreign currency. Base currency is HUF ( Ft ).

![Screen Shot 2023-08-17 at 14 57 56](https://github.com/OCA/account-reconcile/assets/27618042/a877e73c-2c8c-4eaf-bd31-2493ad7f9916)
![Screen Shot 2023-08-17 at 14 56 36](https://github.com/OCA/account-reconcile/assets/27618042/ac24c0a2-0f36-4b28-9638-f0cb401434e0)

**Comment by nagybal** [comment]
@etobella could you please confirm the issue?

**Comment by etobella** [comment]
Hi @nagybal I am not an expert on multicurrency, so a bug might exist.

Can you make a detailed example , show the result and explain the right solution?

This could help me to reproduce it and make the solution.

**Comment by nagybal** [comment]
@etobella thank You in advance

1. At the main accounting settings, you can activate further currencies. 
2. Make any entry for an exchange rate. Date it to the past. It has to be dated before the transactions You make.
3. Create a customer invoice in the secondary currency.
4. Create a transaction and try to reconcile with it

![Screen Shot 2023-08-18 at 10 35 01](https://github.com/OCA/account-reconcile/assets/27618042/6bd3d247-b4f7-454b-ab30-4aae3813adbf)
![Screen Shot 2023-08-18 at 10 42 20](https://github.com/OCA/account-reconcile/assets/27618042/8a11fe61-9bdc-42f8-a319-0fc1c3d68df6)
![Screen Shot 2023-08-18 at 10 45 05](https://github.com/OCA/account-reconcile/assets/27618042/19021cb0-0154-46fd-9d99-8105d5c762ad)
