### ISSUE TITLE
[16.0] generate counterpart entry tax included in price does not show on your bank reconcilliation 

### ISSUE THREAD

**Issue by ameercas** [OCA/account-reconcile#576]
on odoo base  reconcilliation model button to generate counterpart entry tax included in price does not show on your bank reconcilliation wizard. can you bring in the tax column on your wizard and do auto calculations 
![Screenshot 2023-08-18 at 13-59-54 Odoo - expenses](https://github.com/OCA/account-reconcile/assets/45542407/1e12939b-3bb6-40bd-87aa-d6d48dbc6319)
![Screenshot 2023-08-18 at 14-01-21 Odoo - BNK1_2023_00003](https://github.com/OCA/account-reconcile/assets/45542407/d1db1dd0-3e1a-44cd-a53b-5039229f4f38)

**Comment by etobella** [comment]
So true... I made a PR fixing the issue. Can you test it?

**Comment by ameercas** [comment]
> on odoo base reconcilliation model button to generate counterpart entry tax included in price does not show on your bank reconcilliation wizard. can you bring in the tax column on your wizard and do auto calculations ![Screenshot 2023-08-18 at 13-59-54 Odoo - expenses](https://user-images.githubusercontent.com/45542407/261707640-1e12939b-3bb6-40bd-87aa-d6d48dbc6319.png) ![Screenshot 2023-08-18 at 14-01-21 Odoo - BNK1_2023_00003](https://user-images.githubusercontent.com/45542407/261707747-d1db1dd0-3e1a-44cd-a53b-5039229f4f38.png)

Thank You Sir Love it works 100%  Thank you so much for your kind assistance God bless you.

**Comment by ameercas** [comment]
Thank You Sir Love it works 100% Thank you so much for your kind assistance God bless you.
