### ISSUE TITLE
[16.0] Reconciliation Models - Button to generate counterpart entry taxes error.

### ISSUE THREAD

**Issue by ameercas** [OCA/account-reconcile#578]
[Reconciliation Models - Button to generate counterpart entry
taxes in Generate counterpart entry  - once you click on Tax included in Price a popup displays with errors.

on the Bank reconcilliation  the Taxes don't appear,
on odoo base reconcilliation model button to generate counterpart entry tax included in price does not show on your bank reconcilliation wizard. can you bring in the tax column on your wizard and do auto calculations to show the Tax/Vat
![Screenshot 2023-08-22 at 19-13-57 Odoo - New](https://github.com/OCA/account-reconcile/assets/45542407/1b7ec993-6c6d-42d0-a7ed-8967294d1fdc)

**Comment by etobella** [comment]
This seems a problem with Odoo directly. You should open the PR there.
