### ISSUE TITLE
[16.0] account_reconcile_oca Amount field UoM-Currency is incorrect

### ISSUE THREAD

**Issue by nagybal** [OCA/account-reconcile#586]
## Module
account_reconcile_oca

## Describe the bug
Displaying the statement line of the bank in foreign currency, the "Amount" field shows the incorrect currency. The figure itself gets populated correctly. It is the unit of measurement which is incorrect.

**Expected behavior**

**Additional context**
It is a minor thing. Can You reopen and add it to PR577 ?

![Screen Shot 2023-09-06 at 16 00 49](https://github.com/OCA/account-reconcile/assets/27618042/7d0fd749-4dfa-46c0-b7af-b0f9baf61968)

**Comment by nagybal** [comment]
@etobella please take a look

**Comment by etobella** [comment]
Sure! Thanks for checking it :smile:
