### ISSUE TITLE
[16.0.1.2.2] Account Reconcile Oca: Wrong Redirection When Clicking the Journal in the Invoicing Dashboard

### ISSUE THREAD

**Issue by frsfth25** [OCA/account-reconcile#589]
When clicking the Journal in Dashboard, we will be redirected to the view of Account Bank Statement instead of Account Bank Statement Line

## Module
[16.0] Account Reconcile OCA

## Describe the bug
When clicking the Journal in Dashboard, we will be redirected to the view of Account Bank Statement instead of Account Bank Statement Line. Therefore, we won't be able to see the view that is supposed to be showed.

## To Reproduce
**Affected versions**: 16.0

1. Go to Invoicing (in my case, Accounting, since I installed Accounting module made by Odoo Mates)
2. Once in the Dashboard/Overview, scroll down until a Journal appears.
3. Click the Journal Name

**Expected behavior**
We will be redirected to the view of Account Bank Statement Line of the clicked Journal previously.

**Additional context**
OS: Ubuntu 20.04
Browser: Google Chrome
Python: 3.8

**Comment by pedrobaeza** [comment]
I don't get the problem.

**Comment by frsfth25** [comment]
@pedrobaeza pardon my English
but anyway, this is what my senior had done in order to fix the problem:
![image](https://github.com/OCA/account-reconcile/assets/17490925/13501035-281a-4c86-ab43-96a77519a2f3)
he added one overriding method for "open_action" and a new method called "create_cash_statement"

**Comment by pedrobaeza** [comment]
You can propose such change via a pull request, but we need a clear vision of the before and after to be able to evaluate it.

**Comment by frsfth25** [comment]
@pedrobaeza 
yes, you're right,
here's the previous version I used: "version": "16.0.1.0.2",
and here's the latest version I am using: "version": "16.0.1.2.2",
unfortunately I doubt myself in doing that pull request, since I have no experience yet in contributing to this kind of huge project as OCA

**Comment by nagybal** [comment]
@frsfth25 I have the same, but the issue does not seem to be caused by [account-reconcile](https://github.com/OCA/account-reconcile). On their runboat, the issue can not be replicated.

@pedrobaeza does Odoomates have a runboat as well? This is the addon that is probably causing the issue: https://github.com/odoomates/odooapps/tree/16.0/om_account_accountant

**Comment by pedrobaeza** [comment]
I don't know if they provide such service, but anyway, thanks for confirming that is not something of the OCA module. Please contact them.

**Comment by nagybal** [comment]
I have opened a new ticket
https://github.com/odoomates/odooapps/issues/110

@frsfth25  Is this the issue You are facing?

**Comment by frsfth25** [comment]
@nagybal thanks a bunch for the information, 
however, unfortunately it's not the case,

because, what I meant that, as is, the view that appeared once I clicked the Cash journal from Dashboard:
![Screenshot 2023-11-29 080255](https://github.com/OCA/account-reconcile/assets/17490925/065e7afa-b11e-4c97-9d35-abeea51f4d9d)

after adding the code as above, below is the view that appeared once I clicked the Cash journal from Dashboard:
![Screenshot 2023-11-29 080450](https://github.com/OCA/account-reconcile/assets/17490925/063dd39b-8053-4ad6-b46d-29b9718c92e5)

both are in the condition where OM Accounting module was not installed:
![image](https://github.com/OCA/account-reconcile/assets/17490925/45d9be03-9929-431a-877a-a82bdbf51fde)

sorry for the late reply

**Comment by pedrobaeza** [comment]
Please do the tests on a runboat without contamination of other modules.

**Comment by frsfth25** [comment]
@pedrobaeza I can't find Account Reconcile Oca module, how should I add it?
![image](https://github.com/OCA/account-reconcile/assets/17490925/7c79790d-14ef-4517-9ef7-1b79e840ec8f)

**Comment by pedrobaeza** [comment]
Sorry, that's out of scope of this issue tracker. You should know how to deploy to your system modules here from GitHub.
