### ISSUE TITLE
FileParser default value for extra_fields

### ISSUE THREAD

**Issue by ecino** [OCA/account-reconcile#61]
#23 Introduced a problem in file_parser.py:

https://github.com/OCA/bank-statement-reconcile/blob/7.0/account_statement_base_import/parser/file_parser.py#L43

The parameter extra_fields is in fact mandatory as it is now, since it defines the conversion_dict and the keys_to_validate fields. Thus, it should not be named extra_fields anymore, but fields and should not take a None default value. If no value is passed, line 62 will raise an AttributeError (NoneType has no keys)

**Comment by pedrobaeza** [comment]
Can you please make a PR with the changes you mentioned?

Thanks.
