### ISSUE TITLE
[16.0] account_reconcile_oca currency exchange valuation handling issues

### ISSUE THREAD

**Issue by lk-eska** [OCA/account-reconcile#622]
## Module
account_reconcile_oca

## Describe the bug
Currency exchange rates have trash (delete) icon and when clicked new currency exchange lines are created.

## To Reproduce
**Affected versions**: 16.0

1. Create an invoice other than the company currency and confirm
2. Create an operation and try to reconcile it with the invoice created in 1
3. Click on the trash icon at the end of the currency rate difference line 
or click on statement line 
or click on invoice line. 
4. If you try to delete these lines more pops up

**Expected behavior**
Currency exchange difference lines shouldn't have delete option and clicking on lines shouldn't bring new lines.

**Additional context**
There are screenshots of this bug here in this PR:

https://github.com/OCA/account-reconcile/pull/587#issuecomment-1711767810

@etobella  thanks

**Comment by lk-eska** [comment]
An additional problem related to currecy exchange gain/loss lines is that they are left when the invoice is removed. 

I believe it is another side-effect of the same problem.

**Comment by etobella** [comment]
Can you propose a PR fixing it?

**Comment by anajuaristi** [comment]
Hi @etobella 
We are experiencing same issue. The problem is that the issue is blocking the ability of reconcile several invoices. We have no idea how to fix it so... maybe you would be interesed in sending us a quotation? 
If yes, we could contact by email or phone. 
Thank you!!

**Comment by lk-eska** [comment]
@etobella https://github.com/OCA/account-reconcile/pull/636  solves this problem.

There are further problems:

1) there is no way to edit the bank statement line -> we added tree views and it works good. we can send PR for this.
2)  it gets strange when some lines are deleted. for example when invoice is deleted it becomes a seperate line instead of merging into bank temporary account, foreign currency adjustment line remains there. It is wrong until you click reset reconciliation. -> this needs to be handled.
3) amount in currency in the bank statement line is shown in company currency (this is the same in enterprise so i assume this is a common problem but it would be good to fix this)
4) Currency and amount currency selection on Manual Operation screen is necessary.

I can send detailed issues or pull requests. Let me know @etobella

**Comment by etobella** [comment]
A PR would be awesome....

What  are you talking about deletion?

**Comment by lk-eska** [comment]
Here's the PR for listing and editing statement lines: https://github.com/OCA/account-reconcile/pull/637

@etobella

**Comment by lk-eska** [comment]
There are few issues when deleting.

![image](https://github.com/OCA/account-reconcile/assets/80666547/165922bf-0506-4700-ad37-3dfe3b692afe)

102003 -> bank
120000 -> invoice
656000 -> currency exchange
102999 -> temporary account


1) when invoice is deleted, currency exchange line remains there. shouldn't it be removed?
![image](https://github.com/OCA/account-reconcile/assets/80666547/9b81848a-46ea-406b-9363-77babc467dca)

2) when currency exchange line is deleted, it sometimes create a new line with temporary account. see below:
![image](https://github.com/OCA/account-reconcile/assets/80666547/a534a32a-b7cf-48de-bede-7f19cae8aee2)

see the last line. this doesn't always happen, try a few times.

Another issue is that amount currency is actually €120 but it shows 3720₺ in amount in currency. see below:

![image](https://github.com/OCA/account-reconcile/assets/80666547/176e51e3-650f-4a47-83c9-6f5f859193db)

This is also the same in enterprise.

**Comment by lk-eska** [comment]
Finally these fields are required IMO:

https://github.com/OCA/account-reconcile/issues/612

**Comment by lk-eska** [comment]
Should we close this issue or keep it to follow these: https://github.com/OCA/account-reconcile/issues/622#issuecomment-1987968057

@etobella
