### ISSUE TITLE
[16.0] Partial reconciliation

### ISSUE THREAD

**Issue by enricostano** [OCA/account-reconcile#624]
**Is your feature request related to a problem?**
In version 12.0 we have the [account_reconciliation_widget_partial](https://github.com/OCA/account-reconcile/tree/12.0/account_reconciliation_widget_partial) to cover partial reconciliations. I don't see this module migrated to any superior Odoo version. Is this because there are other ways to cover that behavior? Is it covered by the new [account_reconcile_oca](https://github.com/OCA/account-reconcile/tree/16.0/account_reconcile_oca)?

**Describe the solution you'd like**
If it's not covered by the new module, how should we proceed? We would be willing to help with the implementation.

Thanks!

**Comment by etobella** [comment]
Yes, it is covered, just select the line you want to edit and edit the amount on manual operation tab.
