### ISSUE TITLE
[16.0] account_reconcile_oca: problem on bank account in foreign currency

### ISSUE THREAD

**Issue by alexis-via** [OCA/account-reconcile#656]
## account_reconcile_oca

Here is a scenario to reproduce the bug on v16:
1. I have a company with currency = EUR
2. I create a bank journal in currency USD
3. the last EUR/USD exchange rate is dated yesterday with rate = 1.15 € for 1 USD
4. I import the bank statement in USD. I have 1 bank statement line of 1000 USD dated today. Odoo create the account.move.line with amount_currency=1000.0, currency_id=USD and debit/credit = 1150 EUR

at that stage, if I start the bank statement reconcile interface, I get this:

![bank_statement_before_rate_up](https://github.com/OCA/account-reconcile/assets/1157917/e6d06e91-2860-4f48-9a01-9d479b9393dd)

6. the currency rate update cron is executed in the afternoon after the publication of the daily rates by the European Central Bank ; the USD/EUR rate for today becomes 1.20 € (it's an example !)
7. I start the OCA reconcile interface for the bank statement: I get this:

![account_reconcile_oca-after_rate](https://github.com/OCA/account-reconcile/assets/1157917/c0e23dac-9172-4fd6-95db-d75741765e8c)

It shows an amount of 958,33 $... instead of 1000 $ !

When I look at the code here:
https://github.com/OCA/account-reconcile/blob/16.0/account_reconcile_oca/models/account_reconcile_abstract.py#L36
I can see that vals['currency_amount'] is recomputed on the fly from debit/credit using the exchange rate. If I hack that code in the "else" to have amount = line.amount_currency, then I get this:

![hack](https://github.com/OCA/account-reconcile/assets/1157917/0a520f0c-1850-4334-b83c-b637f8610659)

with credit = 1200 € with the value 1150 € of the account.move.line which is crossed out.
I don't understand the logic of the code of account_reconcile_oca on bank journals in foreign currency. I would love to help on this, but I need to understand the design decision for this scenario, to be able to propose a patch.

**Comment by PaulGoubert** [comment]
Hello @etobella, i'm working with Alexis and expecting some hint to understand the logic.  Could you help us ?  Many thanx in advance

**Comment by etobella** [comment]
Uffff, I see the problem.... Let  me think about it :thinking:

**Comment by PaulGoubert** [comment]
Hi @etobella, has a brilliant idea 💡 come to you since Tuesday?   Thank a lot.

**Comment by etobella** [comment]
The issue comes from how is calculated the foreign currency amount, as it is computed on the fly... that is obviously a bad idea and needs to be fixed somehow. However, that was computed that way for some reasons I cannot remember :sob: 

Maybe one option would be to store that information in the JSON in order to avoid this

**Comment by nagybal** [comment]
My understanding is that account_reconcile_oca tries to match by the journal entry not the actual amount in the foreign currency!
https://github.com/OCA/account-reconcile/issues/586

**Comment by alexis-via** [comment]
Thanks for your PR. I tested the specific scenario of this bug with your PR and I get this result:

![fix_oca](https://github.com/OCA/account-reconcile/assets/1157917/7c648f33-ff8a-4950-811f-e19534b74151)

First, we don't see the currency in the column "Amount in currency". 
Second: I don't understand the -1150.00 in the column "Amount in currency" for the line with account 512001. When I look in the database for that line, I see amount_currency=-1000.00 and currency_id=USD, so I don't understand the amount in "Amount in currency" on the second line.

**Comment by alexis-via** [comment]
Here is another scenario, which is a derivative of the above scenario, that I'm testing with the code of PR #668:
I have a supplier invoice dated yesterday (currency rate 1.15 € for 1 USD) for partner Deco Addict for a total amount of 1000 USD. On the payable move line in the purchase journal, I have currency_amount=-1000.00, currency_id=USD and credit=1150.00.

In the bank statement reconcile, when I select this invoice for that bank statement line, I get this:

![oca_fix3](https://github.com/OCA/account-reconcile/assets/1157917/392dc06a-feba-4702-acc3-5e7c848c6782)


For me, there are plenty of problems:
1) on the second line with account 401100, debit should be 1150, so it's difficult for the user to understand what it means to have 1200 € with 1150.00 crossed out. I guess it comes from the temptation to do a partial reconcile... but we want a full reconcile here.
2) on the third line with account = 766000, It displays credit=50.00$... credit should always be in company currency i.e. in EUR. On that line, I would expect to have: Amount in currency = 0.00 and debit=50.00€ (not credit !).
3) the last line with account 512001 should not be there.

**Comment by etobella** [comment]
Yes, i get it.... If we check EE conciliation we get the following:


![image](https://github.com/OCA/account-reconcile/assets/28590170/84648e2b-aa6b-4f46-b377-2e92f327f96e)

**Comment by alexis-via** [comment]
Thank you very much @etobella for all your work on this issue !

I made a test with the latest code of your PR in the scenario described in my last comment:
- company with EUR currency
- vendor bill of 1000 USD with exchange rate of 1.15$=1€
- bank statement line of -1000 USD in USD bank journal with exchange rate of 1.20$=1€
When I select the vendor bill to reconcile in the bank statement interface, I get this:

![closer](https://github.com/OCA/account-reconcile/assets/1157917/232c838a-7049-4c7a-8df4-8668b4caa569)

**Comment by etobella** [comment]
This should work for you?

![image](https://github.com/OCA/account-reconcile/assets/28590170/eeb6230a-c92d-441e-9cbb-d473bc553c9c)

@alexis-via

**Comment by alexis-via** [comment]
I confirm that, with your latest commit, the scenario that I wrote in my previous comment works well in the bank reconcile interface. But, when you look at the result in the journal items, you get a partial reconcile in the payable account and a double entry in the exchange difference expense/revenue account (one in the USD bank journal and one in the exchange rate journal):

![bug_items](https://github.com/OCA/account-reconcile/assets/1157917/06eb2a09-8bc4-4335-9a92-6c04ca38fb8f)

**Comment by PaulGoubert** [comment]
> I confirm that, with your latest commit, the scenario that I wrote in my previous comment works well in the bank reconcile interface. But, when you look at the result in the journal items, you get a partial reconcile in the payable account and a double entry in the exchange difference expense/revenue account (one in the USD bank journal and one in the exchange rate journal):
> 
> ![bug_items](https://private-user-images.githubusercontent.com/1157917/344814278-06eb2a09-8bc4-4335-9a92-6c04ca38fb8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwODE3MDksIm5iZiI6MTcyMDA4MTQwOSwicGF0aCI6Ii8xMTU3OTE3LzM0NDgxNDI3OC0wNmViMmEwOS04YmM0LTQzMzUtOWE5Mi02YzA0Y2EzOGZiOGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDRUMDgyMzI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGQzNzUxMjIwYjkxNDM3YzNmZDkwMTc0Y2ZhOTUzNjZkMWM3ZGNkY2VjYzY4MTM5MjVjMTk4ZmM1MzZjZTIwYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.WCankhqtFqlcD8K9B-8k5Wl5N_j_mZXcEFndENk97Ns)

@etobella

**Comment by etobella** [comment]
I see, actually, Odoo has created a new move that is making this craizy.

Let me review why :sob:

**Comment by etobella** [comment]
I will close the issue in order to keep all the information on the PR
