### ISSUE TITLE
[16.0] account_reconcile_oca makes two fields have the same label

### ISSUE THREAD

**Issue by gjotten** [OCA/account-reconcile#667]
When upgrading `account_reconcile_oca` the following warning gets thrown: 

`Two fields (company_currency_id, currency_id) of account.journal() have the same label: Currency. [Modules: account_reconcile_oca and account] `

In `account_reconcile_oca.pot` we see the following field labeling defined:

```
#. module: account_reconcile_oca
#: model:ir.model.fields,field_description:account_reconcile_oca.field_account_account_reconcile__company_currency_id
#: model:ir.model.fields,field_description:account_reconcile_oca.field_account_account_reconcile__currency_id
#: model:ir.model.fields,field_description:account_reconcile_oca.field_account_bank_statement_line__company_currency_id
#: model:ir.model.fields,field_description:account_reconcile_oca.field_account_journal__company_currency_id
#: model:ir.model.fields,field_description:account_reconcile_oca.field_account_reconcile_abstract__company_currency_id
#: model:ir.model.fields,field_description:account_reconcile_oca.field_account_reconcile_abstract__currency_id
msgid "Currency"
msgstr ""
```

Might I suggest splitting off company_currency_id to be defined as "Company Currency" for good housekeeping and some future-proofing?

**Comment by pedrobaeza** [comment]
Can you please make the PR?

**Comment by gjotten** [comment]
@ddejong-therp

**Comment by jcfernandez-890825** [comment]
@pedrobaeza @gjotten 

Is this solved?

**Comment by gjotten** [comment]
Apologies for not handling this ourselves, it was part of internal cleanup but client work got in the way of course. Thanks @pedrobaeza!
