### ISSUE TITLE
[15 CE] - Calculation error if multiple invoices as counterpart for payment line are used - reconciliation shows balance difference from 0.01

### ISSUE THREAD

**Issue by clxadmin** [OCA/account-reconcile#675]
Module: account_reconciliation_widget
Version: 15.0.1.2.16

Describtion Bug: 
Please see the situation at this Screenshot: https://prnt.sc/an_vRh-Pnut5
I try to reconcile simple payment line entry from imported bank file -- the opposite are 3 bills
debit and credit balance are balanced, but the widget shows a difference of 0.01 - but there is no difference - there seems to be a calculation error in the software

To Reproduce
Version 15 CE

1. One Payment line
2. the opposite are 3 bills
3. debit and credit balance are balanced, but the widget shows a difference of 0.01

Expected behavior
no calculation error

**Comment by pedrobaeza** [comment]
I haven't seen such problem. See at DB level if the amounts of that items are rounded to 2 digits. Maybe the code that is creating such journal items is not doing the rounding.

**Comment by rvalyi** [comment]
may be you may start reading this:
https://medium.com/@olivier.s/demystifying-floating-point-arithmetic-why-0-1-0-2-0-3-673b9c4bcf9a

So yes Odoo is using...
... floats for accounting!

Usually it's possible to round things property at the right place. It's just uterly complicated to program it without mistake and from time to time such bug appear untill theu get fixed. Good luck.

**Comment by pedrobaeza** [comment]
But it's not a problem of the reconciliation widget AFAIK.

**Comment by clxadmin** [comment]
Thank you for the kind advices. :-)
It is clear that this is a rounding problem. It may also be, that it is not just a problem with the reconciliation widget... but I'm facing the error in this module and have to find a way... to reconcile and complete this payment import.

So the pragmatic question is: does anyone have a workaround or idea how I can get rid of this problem? That would be a real help. I also wish myself good luck :-)

**Comment by pedrobaeza** [comment]
I have already told you: look at DB for the debit/credit values of that journal items. If they are not rounded to 2 decimals, you need to round them, and look who is generating that items with the faulty code.

**Comment by clxadmin** [comment]
Hello everyone
I thank you for your hints :-)
Because I don't like making adjustments to a running database, I chose the safe route and divided the payments in the import window into individual payment lines.

This solved the rounding problem of the software or it is simply a workaround
Thanks and have a nice day
