### ISSUE TITLE
[17.0]  Error when install the module account_reconcile_oca

### ISSUE THREAD

**Issue by bootito** [OCA/account-reconcile#687]
When i try install the module account_reconcile_oca throught the App -> import module  i get this issue

The module **account_reconcile_model_oca** is installed and the account_statement_base too

Anyone know what's happening or is a intaller bug?

 while parsing /tmp/tmpbhkf2mk0/account_reconcile_oca/views/res_config_settings.xml:6
Ocurrió un error al validar vista cercana

                    <field name="is_root_company" invisible="1"/>
                    <app data-string="General Settings" string="General Settings" name="general_settings" logo="/base/static/description/settings.png">

                        <div id="invite_users">
                            <block title="Users" name="users_setting_container">

El campo "reconcile_aggregate" no existe en el modelo "res.config.settings"

View error context:
{'file': '/tmp/tmpbhkf2mk0/account_reconcile_oca/views/res_config_settings.xml',
 'line': 4,
 'name': 'res.config.settings form',
 'view': ir.ui.view(2082,),
 'view.model': 'res.config.settings',
 'view.parent': ir.ui.view(735,),
 'xmlid': 'res_config_settings_form_view'}

**Comment by pedrobaeza** [comment]
Import module is an option only for importing data modules (for example, website themes), which is not the case here, where Python code is involved. You have to enter in your server, and add the module in the addons path, reload the service, and all the corresponding deployment stuff.
