### ISSUE TITLE
[16] Impossible to add manually a bank statement line in an existing bank statement

### ISSUE THREAD

**Issue by MatSarr** [OCA/account-reconcile#716]
## Module
account_statement_base 16.0.1.8.0

## Describe the bug
Error: You can't create a new statement line without a suspense account set on the Miscellaneous Operations journal.

## To Reproduce
**Affected versions**: 16

1. open list of bank statement from a bank entry (account.bank.statement&view_type=list)
2. open list of statement line from the bank statement (account.bank.statement.line&view_type=list)
3. clic on "New" and add amount, label and press enter
4.you get the error You can't create a new statement line without a suspense account set on the Miscellaneous Operations journal. IF you don't have a journal type Miscellaneous, you get the error: No journal could be found in company YourCompany for any of those types: general.

**Expected behavior**
Odoo should create a journal entry between the bank account and the suspens account in the bank journal and not the Miscellaneous Operations journal (or the first journal 

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by pedrobaeza** [comment]
Do you have the latest version?

**Comment by MatSarr** [comment]
Yes tried locally with the last version and on the runboat with the last commit. Got the same error.

**Comment by MatSarr** [comment]
Update: When display the journal field in list view we can see that Miscellaneous Operations is pre selected
![image](https://github.com/user-attachments/assets/de79332b-9a68-498c-b71b-6a4ea1ec2df7)

and impossible to choose another journal which is not of type Miscellaneous
![image](https://github.com/user-attachments/assets/570404ee-e090-47a3-b9ea-b366907c1436)

**Comment by victoralmau** [comment]
Fixed with https://github.com/OCA/account-reconcile/pull/719
